modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="creixs_generators"
version="1.0.0"
displayName="Creixs Generators"
authors = "Creixs"
description='''
Adds simple and customizable generators for items, ores etc.
'''

[[dependencies.mygenerator]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mygenerator]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"