modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mygenerator"
version="1.0.0"
displayName="Empty Generator Mod"
description='''
Empty Generator Mod.
'''

[[dependencies.mygenerator]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mygenerator]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"